name: Release

on:
  push:
    branches:
      - main


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Build TypeScript and bundle into asar
        run: pnpm run bundle

      - name: Zip it up!
        run: zip -r release.zip dist
        
      - name: Get some values needed for the release
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          delete_release: true
          tag_name: devbuild
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create the release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: devbuild
          name: Dev Build ${{ steps.vars.outputs.sha_short }}
          draft: false
          prerelease: true
          body_path: .github/release.md
          files: |
            release.zip
